# Generated by Django 3.2.8 on 2021-11-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')])),
                ('is_married', models.IntegerField(choices=[(0, '未婚'), (1, '已婚')])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')])),
                ('teacher', models.ManyToManyField(to='school.Teacher')),
            ],
        ),
    ]
