# Generated by Django 3.2.8 on 2021-11-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bominfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('hw_version', models.CharField(max_length=5, null=True)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('isvalid', models.IntegerField(choices=[(0, '无效'), (1, '有效')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('contacts_name', models.CharField(max_length=50, null=True)),
                ('contacts_phone', models.CharField(max_length=20, null=True)),
                ('contacts_position', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('isvalid', models.IntegerField(choices=[(0, '无效'), (1, '有效')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=100)),
                ('partnumber', models.CharField(db_index=True, default='', max_length=50)),
                ('isvalid', models.IntegerField(choices=[(0, '无效'), (1, '有效')], default=1)),
                ('flag', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Bomlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1, max_length=5)),
                ('references', models.CharField(default='', max_length=1000)),
                ('bominfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.bominfo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.material')),
            ],
        ),
        migrations.AddField(
            model_name='bominfo',
            name='material',
            field=models.ManyToManyField(through='bom.Bomlist', to='bom.Material'),
        ),
        migrations.AddField(
            model_name='bominfo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.project'),
        ),
    ]
