# Generated by Django 3.2.8 on 2021-11-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bominfo',
            old_name='name',
            new_name='bomname',
        ),
        migrations.CreateModel(
            name='Ecn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('state', models.IntegerField(choices=[(0, '未执行'), (1, '已执行')], default=0)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('createtime', models.DateTimeField()),
                ('action', models.IntegerField(choices=[(0, '立即执行'), (1, '消化现有库存后执行')], default=0)),
                ('createdby', models.CharField(max_length=20)),
                ('bominfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.bominfo')),
            ],
        ),
    ]
