# Generated by Django 3.2.8 on 2021-11-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_auto_20211124_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='供应商编码'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contacts_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contacts_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contacts_position',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='供应商名称'),
        ),
    ]
