# Generated by Django 3.2.8 on 2021-11-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0005_auto_20211124_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.category', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='物料编码'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='物料描述'),
        ),
        migrations.AlterField(
            model_name='material',
            name='partnumber',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='物料型号'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.supplier', verbose_name='供应商'),
        ),
    ]
