# Generated by Django 3.2.8 on 2021-11-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0006_auto_20211124_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
