# Generated by Django 3.2.8 on 2021-11-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0008_alter_material_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bom.supplier', verbose_name='供应商'),
        ),
    ]
