# Generated by Django 3.2.8 on 2021-11-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0010_alter_material_isvalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='isvalid',
        ),
    ]
